#!/bin/bash

# Function to install gitlleaks

install_gitleaks() {
    echo "Installing gitleaks..."

        # Installation on Linux-ubuntu
        mkdir -p ~/bin
        export PATH="$HOME/bin:$PATH"
        curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64.tar.gz | tar -xz -C ~/bin
        echo "Gitleaks installed successfully."
}

# Check if gitleaks is enabled in git config
if [[ "$(git config --get hooks.gitleaks)" == "true" ]]; then

    # Install gitleaks if it's not already installed
    if ! command -v gitleaks &> /dev/null; then
        install_gitleaks
    fi

    # Function to check for secrets using gitleaks
    echo "Run gitleaks ..."
	gitleaks protect -v --staged
 
else
    echo "Gitleaks is not enabled. To enable it, use: git config --add hooks.gitleaks true"
fi
